# Generated by Django 5.1.2 on 2024-10-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNo',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
